name: "build"
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
  pull_request:
  release:
    types:
      - released
jobs:
  build:
    strategy:
      matrix:
        java:
          - "17"
        os:
          - "ubuntu-latest"
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Validate Gradle"
        uses: "gradle/actions/wrapper-validation@v3"

      - name: "Setup JDK"
        uses: "actions/setup-java@v4"
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"

      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v3"

      - name: "Build"
        run: "./gradlew build"


      - name: "determine status"
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi

      - name: "publish snapshot"
        if: "${{ env.STATUS != 'release' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_jmpUsername: "${{ secrets.JMP_REPO_USER }}"
          ORG_GRADLE_PROJECT_jmpPassword: "${{ secrets.JMP_REPO_PASSWORD }}"
      - name: "publish release"
        if: "${{ env.STATUS == 'release' && github.event_name == 'release' }}"
        run: ./gradlew publishPlugins
        env:
          ORG_GRADLE_PROJECT_pluginPortalApiKey: "${{ secrets.GRADLE_PLUGIN_PORTAL_KEY }}"
          ORG_GRADLE_PROJECT_pluginPortalApiSecret: "${{ secrets.GRADLE_PLUGIN_PORTAL_SECRET }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_PASSWORD }}"